import os
import io
from typing import Optional, List
from fastapi import FastAPI, Query, HTTPException, UploadFile, File
from fastapi.staticfiles import StaticFiles
from fastapi.responses import FileResponse, JSONResponse
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel
from contextlib import asynccontextmanager
import pandas as pd

from backend.inference import (
    get_metrics,
    get_data,
    load_model_cached,
    get_store_item_history,
    run_forecast,
    compare_all_models,
    forecast_custom_sequence
)

@asynccontextmanager
async def lifespan(app: FastAPI):
    print("[Startup] Initializing Time Series Forecasting Engine...")
    try:
        get_metrics()
        get_data()
        load_model_cached("LSTM")
        print("[Startup] Caches and default neural model initialized successfully.")
    except Exception as e:
        print(f"[Startup Warning] Model/Data preloading notice: {e}")
    yield
    print("[Shutdown] Shutting down Time Series Forecasting Engine.")

app = FastAPI(
    title="Deep Learning Time Series Forecasting API",
    description="Interactive forecasting API comparing MLP, CNN, LSTM, and CNN-LSTM models on store item demand.",
    version="1.0.0",
    lifespan=lifespan
)

# Enable CORS for external frontend or development flexibility
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
STATIC_DIR = os.path.join(BASE_DIR, 'static')
os.makedirs(STATIC_DIR, exist_ok=True)

class ForecastRequest(BaseModel):
    store_id: int = 1
    item_id: int = 1
    model_name: str = "LSTM"
    horizon: int = 30

class CompareRequest(BaseModel):
    store_id: int = 1
    item_id: int = 1
    horizon: int = 30

class CustomForecastRequest(BaseModel):
    values: List[float]
    model_name: str = "LSTM"
    horizon: int = 30

@app.get("/api/health", tags=["Health"])
def health_check():
    """Health check endpoint for cloud hosting platforms and uptime monitors."""
    return {
        "status": "healthy",
        "service": "Deep Learning Time Series Forecasting",
        "version": "1.0.0"
    }

@app.get("/api/metadata")
def api_metadata():
    """Returns available stores, items, and model evaluation scorecards."""
    metrics = get_metrics()
    return {
        "stores": list(range(1, 11)),
        "items": list(range(1, 51)),
        "models": [
            {"id": "LSTM", "name": "LSTM Network", "type": "Recurrent", "val_rmse": metrics.get("LSTM", {}).get("val_rmse", 18.76)},
            {"id": "CNN-LSTM", "name": "CNN-LSTM Hybrid", "type": "Hybrid Spatiotemporal", "val_rmse": metrics.get("CNN-LSTM", {}).get("val_rmse", 19.17)},
            {"id": "CNN", "name": "1D CNN", "type": "Convolutional", "val_rmse": metrics.get("CNN", {}).get("val_rmse", 18.76)},
            {"id": "MLP", "name": "MLP Baseline", "type": "Dense Feedforward", "val_rmse": metrics.get("MLP", {}).get("val_rmse", 18.50)}
        ],
        "default_horizon": 30,
        "max_horizon": 90
    }

@app.get("/api/history")
def api_history(store_id: int = Query(1, ge=1, le=10), item_id: int = Query(1, ge=1, le=50), days: int = Query(90, ge=30, le=365)):
    """Fetch historical sales sequence for store and item."""
    try:
        history = get_store_item_history(store_id, item_id, days)
        return {"store_id": store_id, "item_id": item_id, "days": days, "data": history}
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))

@app.post("/api/forecast")
def api_forecast(req: ForecastRequest):
    """Generates future sales forecast for selected store, item, and model architecture."""
    try:
        result = run_forecast(req.store_id, req.item_id, req.model_name, req.horizon)
        return result
    except FileNotFoundError as fnf:
        raise HTTPException(status_code=503, detail=f"Model not ready: {str(fnf)}")
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))

@app.post("/api/compare")
def api_compare(req: CompareRequest):
    """Compares forecasts generated by all 4 deep learning models."""
    try:
        results = compare_all_models(req.store_id, req.item_id, req.horizon)
        return {
            "store_id": req.store_id,
            "item_id": req.item_id,
            "horizon": req.horizon,
            "comparisons": results
        }
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))

@app.post("/api/forecast-custom")
def api_forecast_custom(req: CustomForecastRequest):
    """Forecast future values from custom sequence array."""
    try:
        result = forecast_custom_sequence(req.values, req.model_name, req.horizon)
        return result
    except Exception as e:
        raise HTTPException(status_code=400, detail=str(e))

@app.post("/api/upload-csv")
async def api_upload_csv(file: UploadFile = File(...), model_name: str = "LSTM", horizon: int = 30):
    """Upload CSV containing 'sales' column to run immediate deep learning forecast."""
    try:
        content = await file.read()
        df = pd.read_csv(io.BytesIO(content))
        # Look for a numeric column named 'sales' or take the first numeric column
        target_col = None
        for col in df.columns:
            if 'sale' in col.lower():
                target_col = col
                break
        if target_col is None:
            numeric_cols = df.select_dtypes(include=['number']).columns
            if len(numeric_cols) > 0:
                target_col = numeric_cols[0]
            else:
                raise ValueError("No numeric data column found in the uploaded CSV.")

        vals = df[target_col].dropna().tolist()
        if len(vals) < 30:
            raise ValueError(f"CSV must contain at least 30 data points, found {len(vals)}.")

        result = forecast_custom_sequence(vals, model_name, horizon)
        return {
            "filename": file.filename,
            "detected_column": target_col,
            "input_points_count": len(vals),
            "result": result
        }
    except Exception as e:
        raise HTTPException(status_code=400, detail=str(e))

# Mount static files
app.mount("/static", StaticFiles(directory=STATIC_DIR), name="static")

@app.get("/")
def serve_index():
    index_file = os.path.join(STATIC_DIR, "index.html")
    if os.path.exists(index_file):
        return FileResponse(index_file)
    return {"message": "Deep Learning Time Series Forecasting API is active. Static frontend file pending."}
